site_name: Build Advanced Interfaces

# This text shows in the footer.
copyright: Digital Initiatives - Bendigo Kangan Institute

nav:
  # The Return to Portal item should always be the first item in the navigation.
  - Return to Portal: /

  # Add additional navigation below this point:
  - Menu:
    - Resources:
      - HTML and CSS:
        - HTML Fundamentals: pages/resources/html-css/html-fundamentals.md
        - CSS Fundamentals: pages/resources/html-css/css-fundamentals.md
      - JavaScript:
        - Variables and Control Flow: pages/resources/javascript/variables-and-control-flow.md
        - Functions: pages/resources/javascript/functions.md
        - Events and the DOM: pages/resources/javascript/events-and-dom.md
        - Async JavaScript and Fetch: pages/resources/javascript/async-and-fetch.md
      - Web Architecture:
        - Data, APIs, and the Frontend: pages/resources/architecture/data-apis-frontend.md
        - Mock APIs: pages/resources/architecture/mock-apis.md
        - Building a Login Page: pages/resources/architecture/building-login-page.md
        - SSR and Frameworks: pages/resources/architecture/ssr-and-frameworks.md
      - NextJS:
        - Routing: pages/resources/nextjs/routing.md
        - Layouts: pages/resources/nextjs/layouts.md
        - TypeScript: pages/resources/nextjs/typescript.md
        - Components: pages/resources/nextjs/components.md
        - Events: pages/resources/nextjs/events.md
        - Arrow Functions: pages/resources/nextjs/arrow-functions.md
        - Hooks: pages/resources/nextjs/hooks.md

    - Tasks:
      - Profile Page: pages/tasks/profile-page.md
      - Style Your Profile: pages/tasks/style-your-profile.md
      - Cafe Website: pages/tasks/cafe-website.md
      - Data and Decisions: pages/tasks/data-and-decisions.md
      - Build a Calculator: pages/tasks/build-a-calculator.md
      - JavaScript Interactivity: pages/tasks/javascript-interactivity.md
      - Interactive Gallery: pages/tasks/interactive-gallery.md
      - Weather Widget: pages/tasks/weather-widget.md
      - Building a Login Page: pages/tasks/building-login-page.md
      - NextJS Application: pages/tasks/nextjs-application.md

# Do not touch anything below this line unless you know what you are doing.
theme:
  name: material
  palette:
    primary: indigo
  features:
    - toc.integrate 
    - navigation.sections
    - navigation.path
    - navigation.footer
    - header.hide
    - content.code.copy
    - content.code.annotate

plugins:
  - enumerate-headings:
      increment_across_pages: true
      # Uncomment below if you would like to reset the table of contents numbering
      # after a certain page:
      restart_increment_after: 
        - pages/tasks/cafe-website.md

extra:
  generator: false

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html

extra_css:
  - extra/style.css
