site_name: Design

# This text shows in the footer.
copyright: Digital Initiatives - Bendigo Kangan Institute

site_url: https://design-docs.netlify.app

nav:
  # The Return to Portal item should always be the first item in the navigation.
  - Return to Portal: https://robocoportal.netlify.app/

  # Add additional navigation below this point:
  - Home: index.md

# Do not touch anything below this line unless you knwo what you are doing.
theme:
  name: material
  palette:
    primary: light blue
  features:
    - toc.integrate 
    - navigation.sections
    - navigation.path
    - navigation.footer
    - header.hide
    - content.code.copy
    - content.code.annotate

plugins:
  - enumerate-headings:
      increment_across_pages: true
      restart_increment_after: 
        - python/tasks/task-1-intro-to-edison.md

extra:
  generator: false

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html

extra_css:
  - extra/style.css
